[package]
name = "code_breaker_v2"
version = "0.1.0"
authors = ["mostlyfocusedmike <mostlyfocusedmike@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
